language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/phpcs-cache

php:
  - 7.2
  - 7.3
  - 7.4

env:
  matrix:
    - RUN_TESTS=1 SYMFONY=5.* # dev
    - RUN_TESTS=1 SYMFONY=4.* # dev
    - RUN_TESTS=1 SYMFONY=3.* # dev
    - RUN_TESTS=1 SYMFONY=5.* COMPOSER_EXTRA_ARGS="--prefer-stable"
    - RUN_TESTS=1 SYMFONY=4.* COMPOSER_EXTRA_ARGS="--prefer-stable"
    - RUN_TESTS=1 SYMFONY=3.* COMPOSER_EXTRA_ARGS="--prefer-stable"
    - RUN_TESTS=1 SYMFONY=5.* COMPOSER_EXTRA_ARGS="--prefer-lowest --prefer-stable"
    - RUN_TESTS=1 SYMFONY=4.* COMPOSER_EXTRA_ARGS="--prefer-lowest --prefer-stable"
    - RUN_TESTS=1 SYMFONY=3.* COMPOSER_EXTRA_ARGS="--prefer-lowest --prefer-stable"

matrix:
  fast_finish: true
  include:
    - php: 7.4
      env: SYMFONY=5.* COMPOSER_EXTRA_ARGS="--prefer-stable" COVERAGE="--coverage ./coverage.xml --coverage-src ./src" TESTER_RUNTIME="phpdbg"
    - php: 7.4
      env: RUN_TESTS=0 SYMFONY=5.* COMPOSER_EXTRA_ARGS="--prefer-stable" PHPSTAN=1
    - php: 7.4
      env: RUN_TESTS=0 SYMFONY=5.* COMPOSER_EXTRA_ARGS="--prefer-stable" CODING_STANDARD=1
  exclude:
    - php: 7.4
      env: SYMFONY=4.* COMPOSER_EXTRA_ARGS="--prefer-stable"
  allow_failures:
    - env: RUN_TESTS=1 SYMFONY=5.*
    - env: RUN_TESTS=1 SYMFONY=4.*
    - env: RUN_TESTS=1 SYMFONY=3.*

before_install:
  - if [[ $SYMFONY = '3.*' ]]; then composer require --no-update symfony/console:^3.0; fi
  - if [[ $SYMFONY = '4.*' ]]; then composer require --no-update symfony/console:^4.0; fi
  - if [[ $SYMFONY = '5.*' ]]; then composer require --no-update symfony/console:^5.0; fi
  - travis_retry composer self-update

install:
  - travis_retry composer update --no-interaction --no-suggest --no-progress --prefer-dist $COMPOSER_EXTRA_ARGS # update because we may need --prefer-lowest option

script:
  - if [ "$PHPSTAN" = "1" ]; then vendor/bin/phpstan analyse -l 2 -c phpstan.neon src tests/KdybyTests; fi
  - if [ "$CODING_STANDARD" = "1" ]; then vendor/bin/phpcs --standard=ruleset.xml --cache=$HOME/phpcs-cache/.phpcs-cache --encoding=utf-8 -sp src tests/KdybyTests; fi
  - if [ "$CODING_STANDARD" = "1" ]; then vendor/bin/parallel-lint -e php,phpt --exclude vendor .; fi
  - if [ "$RUN_TESTS" = "1" ]; then vendor/bin/tester $COVERAGE -s -p ${TESTER_RUNTIME:-php} -c ./tests/php.ini-unix ./tests/KdybyTests/; fi

after_script:
  - if [ "$COVERAGE" != "" ]; then vendor/bin/php-coveralls --verbose --config tests/.coveralls.yml || true; fi

after_failure:
  - 'for i in $(find ./tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done'
